### ISSUE TITLE
NonEmpty folds?

### ISSUE THREAD

**Issue by Profpatsch** [Gabriella439/foldl#177]
In some situations, having a proof that the fold always iterates over at least one element makes the whole thing easier to handle.

e.g. I have a list of elements, and I want to say “if the element `x` appears, use the timestamp from `x`, otherwise return the timestamp from the first element.

```
do
  timestampFromX <- Fold.find isX <&> (.timestamp)
  timestampFromFirst <- Fold.head
  pure (timestampFromX & fromMaybe timestampFromFirst)
```

^ This can only be written if `Fold.head` can return a `Timestamp`, but because `Fold`s always have to deal with the empty stream, this returns `Maybe Timestamp`.

My lazy idea at a project-local implementation is to define

`newtype FoldNE a b = FoldNE (Fold a b)`

and only inherit `Extend` and not inherit `Comonad`, then define some wrappers which unwrap the `Nothing` cases with an `error`. Accordingly all functions have to be wrapped as necessary to use the NE type, but that’s a constant time overhead.

**Comment by Profpatsch** [comment]
Ah, I noticed my conceptual mistake;

```haskell
foldNE :: Foldable1 f => FoldNE a b -> f a -> b
foldNE (FoldNE (Fold.Fold step _begin done)) xs = case xs & toNonEmpty of
  init :| rest -> Fold.fold (Fold.Fold step init done) rest
```

does not typecheck, because the `init` in `Fold` has to be `:: x`, but the init in the list is `:: a`.

**Comment by Profpatsch** [comment]
Nevermind, I can just define it as 

```
newtype FoldNE a b = FoldNE (Fold a b)
  deriving newtype (Profunctor, Semigroupoid, Applicative, Functor, Extend, Monoid, Semigroup, Floating, Num, Fractional)

foldNE :: Foldable1 f => FoldNE a b -> f a -> b
foldNE (FoldNE f) = Fold.fold f

liftFold :: Fold a b -> FoldNE a b
liftFold f = FoldNE f

headNE :: FoldNE a a
headNE =
  liftFold $
    Fold.head <&> \case
      Nothing -> error "FoldNE always has a first element"
      Just a -> a

listNE :: FoldNE a (NonEmpty a)
listNE =
  liftFold $
    Fold.list <&> nonEmpty <&> \case
      Nothing -> error "FoldNE always has at least one list element"
      Just as -> as
```

… and it seems to work, cause the `begin` field will never be looked at if the list is not empty, e.g.

```
> foldNE headNE ('c' :| [])
'c'
```

**Comment by Gabriella439** [comment]
@Profpatsch: I think there is a total solution that would work which is:

```haskell
newtype Fold1 a b = Fold1 (a -> Fold a b)

fold1 :: Fold1 a b -> NonEmpty a -> b
fold1 (Fold1 k) (a :| as) = fold (k a) as

head :: Fold1 a b
head = Fold1 (\begin -> Fold const begin id)

nonEmpty :: Fold1 a (NonEmpty a)
nonEmpty = Fold1 (\x -> fmap (x :|) list)
```

**Comment by Profpatsch** [comment]
Oh fantastic, I had a glimpse of this solution in my head at one point but lost it again and decided to go for the more “pragmatic” solution first!

This is awesome!
