### ISSUE TITLE
Fold1: provide non-empty container folds

### ISSUE THREAD

**Issue by Profpatsch** [Gabriella439/foldl#183]
e.g. 

```
nonEmpty :: Fold1.Fold1 a (NonEmpty a)
nonEmpty = Fold1.Fold1 $ \init -> fmap (init :|) Original.list
```

Maybe it makes sense to invoke a dependency on https://hackage.haskell.org/package/nonempty-containers ?

**Comment by Profpatsch** [comment]
I’ve got another function I needed:

```
concatMap1 :: Semigroup x => (a -> x) -> (x -> b) -> Fold1 a b
concatMap1 to extract = Fold1 $ \begin -> Fold (\x a -> x <> (to a)) (to begin) extract
```

**Comment by Gabriella439** [comment]
I probably wouldn't implement `concatMap1` because you can derive it from `Control.Foldl.NonEmoty.sconcat` and `dimap`

**Comment by Gabriella439** [comment]
Closed by #186

**Comment by Profpatsch** [comment]
> you can derive it from `Control.Foldl.NonEmoty.sconcat` and `dimap`

yeah, however `dimap` is not the first thought I have when I think about `concatMap` :)

**Comment by Gabriella439** [comment]
Even still, the function you propose is not the type signature I would expect for a function named `concatMap1`.  I would have expected a type signature like this one:

```haskell
concatMap1 :: Semigroup b => (a -> b) -> Fold1 a b
```

**Comment by Profpatsch** [comment]
I meant `foldMap1`, analogous to `foldMap` from `Control.Foldl`.
