### ISSUE TITLE
Proposal: postMapM and foldToFoldM

### ISSUE THREAD

**Issue by adamConnerSax** [Gabriella439/foldl#204]
I often find these useful
```haskell
postMapM :: Monad m => (a -> m b) -> FoldM m x a -> FoldM m x b
postMapM f (FoldM step begin done) = FoldM step begin done'
  where done' x = done x >>= f

foldToFoldM :: Fold x (m b) -> FoldM m x b 
foldToFoldM = postMapM id . generalize
```
I'd be happy to submit a PR if they would be accepted as utilities. And I'm not sure those are the best names, though I'm quite fond of ```postMapM```

**Comment by Gabriella439** [comment]
I'd accept a PR for `postMapM` (it obeys nice laws), but `foldToFoldM` seems a little idiosyncratic

**Comment by adamConnerSax** [comment]
Made the PR (https://github.com/Gabriella439/foldl/pull/205). I also noticed what might be a typo in the documentation for premapM. The functor-law-like thing has ```premap``` on the rhs instead of ```premapM```.  

I understand why you find foldToFoldM idiosyncratic and I left it out of the PR. But, FWIW, I use it fairly often. Maybe my use-cases or style are unusual here...
